version: '3'

services:
  movie_app_backend:
    build: .
    container_name: movie_app_backend
    restart: always
    ports:
      - "8080:8080"  # Map the application port
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/spring  # Use the service name 'database' as the host to connect to the PostgreSQL container
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: changeme
    depends_on:
      - database  # Make sure the database service is up and running before starting the application service

  database:
    image: postgres:latest
    container_name: moviebapp_database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: spring
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
